import type {Axis,Lesson,Question} from './model.ts';

export const backroadsGroups=[
 {id:9,title:'The scenic route',note:'Familiar names, unexpected stories.'},
 {id:10,title:'A few good surprises',note:'Neighbors, islands, and changing tastes.'},
 {id:11,title:'Better table talk',note:'Useful detours for your next shift.'},
 {id:12,title:'Follow your curiosity',note:'A little context. A better question.'},
];
const q=(prompt:string,answer:string,b:string,c:string,why:string):Question=>({prompt,options:[answer,b,c],correct:0,why});
const lesson=(id:string,title:string,chapter:number,axis:Axis,hook:string,story:string,labels:string,takeaway:string,questions:Question[],sources:string[],relatedLessons:string[]):Lesson=>({
 id:`br-${id}`,title,chapter,axis,collection:'backroads',secondaryConnections:[],prerequisites:{all:[],any:[]},relatedLessons,tastingConnections:[],kind:id==='unknown-bottle'?'scenario':'lesson',revision:2,
 centralIdea:hook,subtitle:hook,sentences:story.split('|'),visual:{kind:'process',labels:labels.split('|')},takeaway,questions,sources,
});
export const backroadsLessons:Lesson[]=[
lesson('rhone','Côtes du Rhône: the useful bridge',9,'place','A French place name you can bring to an ordinary Tuesday.',
'Côtes du Rhône is a broad Rhône Valley appellation, not a single grape or a promise of one price.|Many of its southern reds blend Grenache, Syrah, and Mourvèdre, combining generous fruit with spice and structure.|That makes the region a useful bridge from familiar, friendly reds toward more specific Rhône villages and crus.|For a guest who wants a satisfying red without a grand ceremony, check this bottle’s blend, body, and price first.',
'Broad region|Village names|Individual crus','“If you like a generous red with some spice, this is a good place to look.”',[
q('Côtes du Rhône names…','An appellation','A single grape','A producer','The place comes first; the blend still needs checking.'),
q('A common southern Rhône red partnership is…','Grenache, Syrah, Mourvèdre','Pinot Noir, Gamay, Cabernet Franc','Chardonnay, Sauvignon Blanc, Riesling','These grapes contribute different pieces to many southern blends.'),
q('Does the regional name guarantee a cheap bottle?','No; check the actual bottle and price','Yes, all regional wines cost the same','Only if the vintage is young','A useful value lead is not a price guarantee.'),
q('A guest likes generous, spicy reds. Your next step?','Check this wine’s blend and style','Promise every Rhône wine tastes alike','Recommend solely by the label’s prestige','Translate the regional clue into a specific recommendation.')],['br-rhone'],['br-syrah','br-old-new']),
lesson('syrah','Syrah vs. Shiraz',9,'grape','One grape. Two names. Quite a wardrobe.',
'Syrah and Shiraz are names for the same grape, not competing varieties.|Syrah is the familiar Rhône name; Shiraz became the customary Australian name.|A Syrah label may suggest a peppery, restrained style and Shiraz may suggest riper fruit, but cool Australian sites and producer choices happily disrupt that shortcut.|Compare climate and the producer’s description before promising either style to a guest.',
'Same grape|Different traditions|Check the bottle','“Same grape; this producer’s version is the part worth exploring.”',[
q('Syrah and Shiraz are…','The same grape','Different grape families','A red and a white grape','The names reflect traditions and sometimes stylistic intent.'),
q('Which is the customary Australian name?','Shiraz','Sangiovese','Sherry','Shiraz is a grape name; Sherry is a different wine category.'),
q('An Australian Syrah is impossible. True?','No; producers can use either name','Yes; the grape changes at the border','Only if it is a blend','A country is not a fixed flavor setting.'),
q('What makes your style prediction stronger?','Site, climate, and producer information','The spelling alone','Bottle weight','Use the name as a first clue, then check.')],['br-shiraz'],['br-rhone','br-old-new']),
lesson('orange','Orange wine: the skins stayed over',9,'technique','No oranges were squeezed in the making of this lesson.',
'Orange or amber wine is made from white grapes with skin contact, which can add color, aroma, and drying grip.|Georgia’s qvevri tradition uses clay vessels and preserves a long history of this approach, though skin-contact whites need not be Georgian or made in clay.|Renewed interest in older techniques helped bring the style to more wine lists; the tradition itself never needed inventing again.|Tell a guest about this bottle’s texture and sweetness rather than assuming that orange means sweet, funky, or natural.',
'White grapes|Skins stay in contact|Color + texture','“It’s a white-grape wine with some of the grip you might expect from a red.”',[
q('Orange wine usually gets its color from…','White-grape skin contact','Orange juice','A required red-wine blend','The skins change the wine; citrus fruit is not the ingredient.'),
q('A qvevri is…','A traditional clay winemaking vessel','A grape variety','A sweetness category','Georgia’s vessel tradition is one part of this wider story.'),
q('Must every skin-contact white taste funky?','No','Yes','Only after chilling','Skin contact describes a technique, not one fixed aroma.'),
q('What should you explain before pouring?','The specific wine’s grip and style','That it is automatically sweet','That orange always means organic','Texture is useful; category stereotypes are less useful.')],['br-georgia','skin'],['br-farming','br-glass']),
lesson('1855','Bordeaux 1855: a very durable list',9,'place','An exhibition needed a ranking. Wine kept the paperwork.',
'For the 1855 Paris exhibition, Bordeaux brokers ranked prominent estates using reputation and trading prices.|The red list has five ranks, or growths, mostly in the Médoc with Haut-Brion as the Graves exception; sweet Sauternes and Barsac have a separate list.|A growth is a classified estate’s rank, not the age of its vines or a score for every new vintage.|The largely preserved ranking still shapes reputation and price, but it cannot tell you whether tonight’s guest will enjoy tonight’s bottle.',
'1855 exhibition|Reputation + prices|A lasting classification','“First growth is a historical rank, not a guarantee that it’s your favorite wine.”',[
q('What prompted the 1855 classification?','The Paris exhibition','A modern blind-tasting competition','A new grape disease','The list began as a way to present established wines at an exhibition.'),
q('What did brokers use in ranking estates?','Reputation and trading prices','Bottle weight','The average age of each vine','Commercial history was part of the classification’s foundation.'),
q('A “growth” here means…','A classification rank','A harvest season','A grape’s growth rate','It is a historical hierarchy of estates.'),
q('Does 1855 rank every Bordeaux estate?','No','Yes, including every Right Bank estate','Only all white-wine estates','Its scope is specific; Bordeaux has other places and classifications.')],['br-1855'],['br-bordeaux','br-vintage']),
lesson('finger-lakes','Finger Lakes: the lakes do some work',9,'place','American wine has an East Coast, too.',
'New York’s Finger Lakes is a cool-climate wine region where deep lakes moderate nearby vineyard temperatures.|Riesling is a signature grape, and its acidity helps it carry styles from dry to sweet.|The lakes matter, but slope, airflow, and vineyard position still make neighboring sites different.|Offer it as a fresh American alternative, then check sweetness rather than treating either Riesling or New York as a flavor guarantee.',
'New York|Deep lakes|Cool-climate Riesling','“An American Riesling with refreshing acidity; let’s check how dry this one is.”',[
q('Where are the Finger Lakes?','New York','Northern California','Oregon','This detour takes us well east of the Pacific vineyards.'),
q('What do the lakes help do?','Moderate nearby temperatures','Make all vineyards identical','Eliminate every frost risk','They influence climate without removing vineyard differences or risk.'),
q('Must Finger Lakes Riesling be sweet?','No; styles range from dry to sweet','Yes','Only when served cold','Always check the individual wine’s sweetness.'),
q('A guest wants a fresh American white. What helps?','Describe this bottle’s acidity and sweetness','Promise it tastes like all German Riesling','Recommend by state alone','Origin introduces the wine; its actual balance makes the recommendation.')],['br-finger-lakes'],['br-vintage','br-other-whites']),
lesson('napa-sonoma','Napa vs. Sonoma: neighbors, not twins',10,'place','The county line is not a flavor switch.',
'Napa and Sonoma are neighboring Northern California wine regions with varied terrain and cooling influences.|Napa is especially associated with Cabernet Sauvignon, while Sonoma stretches across coastal and inland sites suited to many varieties.|Fog, ocean exposure, elevation, and the particular vineyard matter more than a cartoon of one region as always bigger or better.|At the table, compare two actual wines by grape, body, oak, and price rather than staging a county rivalry.',
'Neighboring regions|Many climates|Two actual bottles','“Let’s compare the style of these two wines, rather than choose a winner by county.”',[
q('Napa and Sonoma are…','Neighboring but varied regions','Two names for one vineyard','Grape varieties','They share a neighborhood, not a single identity.'),
q('A useful climate clue is…','Ocean exposure and fog','Label font','County reputation alone','Site details help explain ripening and style.'),
q('Is every Sonoma wine lighter than every Napa wine?','No','Yes','Only for red wines','Both contain diverse vineyards and producer choices.'),
q('How do you help a guest choose?','Compare grape, body, oak, and price','Rank the counties','Assume the pricier region suits everyone','Specific comparisons make a broad geography useful.')],['br-napa','br-sonoma'],['br-old-new','br-vintage']),
lesson('port','Port: a well-timed interruption',10,'technique','Sometimes the yeast does not get to finish its dinner.',
'Port is a fortified wine from Portugal’s Douro region, made by adding grape spirit during fermentation.|That interruption leaves grape sugar and raises alcohol, so ordinary red-wine serving assumptions need adjusting.|Ruby styles emphasize fruit, while aged tawny styles develop nuttier, more oxidative notes; Vintage and Late Bottled Vintage are distinct categories, not interchangeable names.|Use the house’s smaller fortified-wine pour and ask whether the guest prefers fruitier or nuttier flavors.',
'Fermentation begins|Grape spirit added|Sugar retained','“Would you like a fruit-led Port or something with more nutty, aged character?”',[
q('Why does Port retain grape sugar?','Spirit interrupts fermentation','All sugar is added after bottling','The bottle stops grapes ripening','Fortification changes the yeast’s environment before all sugar is consumed.'),
q('Where is Port produced?','The Douro region of Portugal','Any warm wine region','Only the city of Porto','The wine’s origin is the demarcated Douro region.'),
q('Which contrast is useful?','Ruby fruit vs. aged tawny nutty notes','Ruby dry vs. tawny always sugar-free','White grapes vs. orange fruit','This is a style starting point; check the exact category and bottle.'),
q('Should you default to a normal table-wine pour?','No; follow the fortified-wine pour','Yes, alcohol is the same','Only for Vintage Port','Port is generally stronger, so use the restaurant’s appropriate serving size.')],['br-port'],['br-madeira','br-glass']),
lesson('madeira','Madeira: the happy accident became the plan',10,'technique','Heat and oxygen: usually a warning, here part of the recipe.',
'Madeira is a fortified wine from a Portuguese Atlantic island, shaped by a history of warm sea journeys.|Its deliberate heating and oxidative aging develop a style that would be damage in many other wines.|Controlled heating and slower warm-cask aging offer different routes, producing wines with bright acidity across dry to sweet styles.|Madeira can be remarkably long-lived, but still check the producer’s storage advice and describe this bottle’s sweetness before serving.',
'Island wine|Heat + oxygen|A deliberate style','“That nutty character is intentional here; let’s find the sweetness level you enjoy.”',[
q('Heat and oxygen in Madeira production are…','Deliberate parts of the style','Always accidental faults','A way to remove all alcohol','Context matters: a production choice here can be damage elsewhere.'),
q('Madeira comes from…','A Portuguese Atlantic island','Bordeaux','The Douro Valley','Port and Madeira share fortification, not an origin.'),
q('Is all Madeira equally sweet?','No; styles range from dry to sweet','Yes','Only the older bottles are dry','Acidity and sweetness both matter to the recommendation.'),
q('An old Madeira is automatically perfect. True?','No; check condition and producer guidance','Yes, storage never matters','Yes, if the label is expensive','Longevity is a strength, not a promise about every bottle.')],['br-madeira'],['br-port','br-vintage']),
lesson('merlot','Merlot: the grape survived the reviews',10,'grape','A film can change a conversation. It cannot change a grape.',
'Merlot became a familiar American choice, helped by approachable styles and a name many guests knew.|The 2004 film Sideways supplied a memorable insult, but its effect should not be confused with the whole history of Merlot demand.|Fashion, planting decisions, price, and wine quality all matter; serious Merlot never stopped existing in Bordeaux or elsewhere.|If a guest is skeptical, describe this wine’s fruit, texture, and structure rather than arguing with a movie at the table.',
'Popularity|Cultural backlash|Taste the bottle','“Let’s judge this Merlot by what’s in the glass, not by the punchline.”',[
q('What did Sideways change most directly?','A cultural conversation about grapes','Merlot’s genetics','Bordeaux’s legal borders','A memorable story can affect reputation without changing the grape.'),
q('Can one movie explain all market changes?','No','Yes','Only in California','Many commercial and cultural factors move together.'),
q('Did good Merlot cease to exist?','No','Yes, until a new grape was bred','Only blends survived','A grape’s reputation and a specific wine’s quality are different things.'),
q('A guest dismisses Merlot. A helpful response?','Offer a concrete style comparison','Lecture them about cinema','Hide the grape name','Respect the guest and describe the bottle honestly.')],['br-sideways','bordeaux'],['br-bordeaux','br-drinkers']),
lesson('drinkers','Who drinks what? Ask the person.',10,'technique','A generation is a very large dinner party to generalize about.',
'Wine tastes move with food, travel, price, availability, and the occasions people want to share.|A younger guest may enjoy a classic Bordeaux, while an older guest may be curious about skin-contact wine; age is not an order form.|Treat claims about what is trending as dated observations from a named market, not permanent rules about everyone.|For tonight’s table, ask about familiar favorites, budget, and curiosity, including whether anyone would prefer something without alcohol.',
'Market observation|Date + context|Ask this guest','“Something familiar tonight, or are you in the mood to explore?”',[
q('A guest’s age reliably tells you their wine order. True?','No','Yes','Only for sparkling wine','People do not order as statistical averages.'),
q('What makes a trend claim useful?','A date, market, and named source','The word everyone','A viral post without context','Keep observations maintainable and specific.'),
q('What can change wine preferences?','Food, price, availability, and occasion','Only birth year','Only formal training','Preferences have many influences and can change.'),
q('What should you ask this table?','Favorites, budget, and interest in exploring','Which demographic category they fit','Why they do not follow a trend','Their own answers are better service data than stereotypes.')],['hospitality'],['br-merlot','br-language']),
lesson('bordeaux','Bordeaux lore: rivers, merchants, and reputations',11,'place','The famous names sit inside a much larger wine world.',
'Bordeaux’s Left Bank often leans toward Cabernet Sauvignon, while Right Bank blends often give Merlot a larger role, with plenty of producer-specific detail.|Names such as Lafite on the Left Bank and Pétrus in Pomerol carry cultural weight, but most Bordeaux is not a trophy bottle.|Merchants, known as négociants, connect many estates to markets, helping explain the region’s long commercial reach.|Blend, vintage, storage, and price still matter more to a useful recommendation than reciting famous estates.',
'Rivers + banks|Estates + merchants|Bottle + vintage','“The bank gives us a clue about the blend; the producer gives us the details.”',[
q('Which is a useful starting tendency?','Left Bank Cabernet; Right Bank Merlot','Every Bordeaux is 100% Cabernet','All Right Bank wine is sweet','It is a broad blend clue with exceptions, not a recipe.'),
q('A négociant is…','A wine merchant','A fermentation vessel','A grape variety','Merchants help connect producers with markets.'),
q('Does Pétrus represent the price of all Bordeaux?','No','Yes','Only in good vintages','Famous estates are a small part of a large region.'),
q('What matters for tonight’s bottle?','Blend, vintage, storage, and guest preference','Name recognition alone','The number of famous neighbors','Prestige is context, not the whole service conversation.')],['bordeaux','br-bordeaux-trade'],['br-1855','br-business']),
lesson('other-whites','Albariño, Pinot Blanc & Verdejo',11,'grape','Three more ways to answer “What else is there?”',
'Albariño, closely associated with Spain’s Atlantic Rías Baixas, often offers vivid acidity and citrus or stone-fruit aromas.|Pinot Blanc can offer a gentler, rounded white-wine profile; an Alsace bottle labeled Pinot Blanc may also include Auxerrois.|Verdejo, strongly associated with Spain’s Rueda, often combines freshness with herbal notes and a lightly bitter finish.|Use these as comparison points for familiar white-wine drinkers, then check oak, sweetness, and the individual producer’s style.',
'Albariño · bright|Pinot Blanc · supple|Verdejo · herbal','“Would you rather explore bright and citrusy, softer and rounded, or fresh and herbal?”',[
q('Albariño is strongly associated with…','Rías Baixas','Bordeaux’s red blends','Madeira fortification','Atlantic Galicia is an important home for Albariño.'),
q('Why check an Alsace Pinot Blanc label carefully?','It may include Auxerrois','It must be a red wine','It always means Chardonnay','Regional labeling and exact blends reward a quick check.'),
q('Verdejo is closely associated with…','Rueda','Champagne','The Finger Lakes','Place can help you remember an unfamiliar grape.'),
q('How should you introduce these whites?','Compare style, then verify the bottle','Promise they are identical','Assume none can see oak','A comparison is a bridge, not a claim that two wines are the same.')],['br-albarino','br-pinot-blanc','br-verdejo'],['br-language','br-unknown-bottle']),
lesson('language','Describe wine without sounding ridiculous',11,'technique','If the guest understands you, the words are doing their job.',
'Aroma is what you smell; flavor includes the impression you get while tasting, with smell doing much of the work.|Then separate sweetness, mouth-watering acidity, drying tannin, body, and the length of the finish.|Choose two or three familiar comparisons instead of a theatrical inventory of fruit and antique furniture.|“Dry, crisp, and citrusy” gives someone a usable picture, while a follow-up question checks whether that picture sounds appealing.',
'Aroma + flavor|Texture + balance|A useful sentence','“Dry, medium-bodied, with plum-like fruit and a little grip. Does that sound good?”',[
q('Which word describes a drying sensation?','Tannin','Acidity','Finish','Separate texture from smells and from mouth-watering acidity.'),
q('Finish describes…','How long the impression lasts','The label’s final word','How quickly the server pours','Length is a sensory observation, not an automatic quality verdict.'),
q('What makes a descriptor useful?','It helps this guest imagine the style','It sounds expensive','Nobody else understands it','Communication is the point of the vocabulary.'),
q('After describing a wine, what helps?','Ask whether that style appeals','Keep adding obscure aromas','Correct the guest’s associations','Shared understanding beats a performance.')],['mouthfeel','styles','hospitality'],['br-glass','br-unknown-bottle']),
lesson('glass','Wine changes in the glass',11,'technique','The first sip is an introduction, not a sworn statement.',
'A very cold wine can seem less aromatic; as it warms, more of its character may become noticeable.|Air and time can change aromas too, which is why tasting again can be more useful than deciding instantly.|Decanting can separate sediment or expose wine to air, but fragile older wines do not all benefit from a long, vigorous airing.|Follow house practice and the producer’s guidance, taste if appropriate, and check back with the guest rather than promising a decanter will fix every problem.',
'Temperature|Air + time|Taste again','“Let’s give it a little time in the glass, then see what changes.”',[
q('A very cold white seems muted. What might help?','Let a small pour warm slightly','Assume it has no aroma','Heat the bottle rapidly','A little temperature change can reveal aroma without a dramatic intervention.'),
q('Decanting can help with…','Sediment separation or aeration','Removing all wine faults','Making every wine younger','The purpose depends on the wine and its condition.'),
q('Every old red needs hours of air. True?','No','Yes','Only if it has sediment','Fragile wines may fade; assess and follow guidance.'),
q('A guest reports a possible fault. You should…','Check it through the house process','Promise air will cure it','Wait until the bottle is finished','A concern deserves attention, not a universal decanting solution.')],['br-service','faults'],['br-vintage','br-language']),
lesson('old-new','Old World, New World: a shortcut with potholes',11,'place','A map label is not a tasting note.',
'Old World usually refers to established European wine traditions and nearby historic wine regions; New World usually refers to places such as the Americas, Australia, and New Zealand.|People often use the terms as shorthand for restrained versus ripe styles, but cool New World sites and warm Old World sites complicate that story.|The terms also hide ancient winemaking outside the usual European spotlight, including Georgia’s long tradition.|Use the shortcut to begin a conversation, then replace it with actual climate, grape, producer, and cellar choices.',
'Broad shorthand|Plenty of exceptions|Specific bottle','“That’s a useful first clue, but this vineyard and producer tell us more.”',[
q('Do Old World and New World determine flavor?','No','Yes','Only for red wines','The categories are broad cultural geography, not a flavor law.'),
q('A cool New World vineyard can make…','A fresh, restrained wine','Only a rich, high-alcohol wine','Only sparkling wine','Climate and choices can contradict the shortcut.'),
q('What does the shorthand risk overlooking?','Older traditions outside the usual spotlight','All European wine','Every labeled grape','The history of wine is bigger than a tidy two-column chart.'),
q('What should replace a broad prediction?','Actual site, grape, and producer information','The country’s reputation alone','The bottle shape','Specific evidence improves the recommendation.')],['br-napa','br-sonoma','br-georgia'],['br-syrah','br-finger-lakes']),
lesson('vintage','Vintage: weather with a year attached',12,'place','A year is a clue, not a review.',
'Vintage identifies the grape harvest year, and that season’s weather can influence ripeness, acidity, yields, and disease pressure.|Year-to-year differences may be especially noticeable in challenging climates, but vineyard work, selection, and winemaking also shape the result.|Some producers blend across years for a consistent style, as in many non-vintage Champagnes; a famous year still does not guarantee every bottle.|For a guest, connect vintage to expected style and bottle condition rather than treating older or more celebrated as automatically better.',
'Harvest weather|Producer decisions|Condition today','“The year helps explain the style; storage and the producer matter too.”',[
q('Vintage normally means…','The harvest year','The bottling year','The purchase year','The grapes’ growing season is the reference point.'),
q('Why might two vintages differ?','Weather and producer responses','Only the label design','Because wine ages exactly alike','Weather affects the crop, and decisions affect how it becomes wine.'),
q('Why blend wines from different years?','To help create a consistent style','To avoid all quality control','To guarantee sweetness','A non-vintage blend can be a deliberate stylistic tool.'),
q('A famous vintage guarantees a great bottle. True?','No','Yes','Only if it is expensive','Producer, handling, storage, and personal preference still matter.')],['br-champagne-blending','terroir'],['br-1855','br-glass']),
lesson('business','The strange business of wine',12,'technique','That bottle has usually met a few people before meeting you.',
'A bottle may travel from producer through an importer and distributor before reaching a restaurant, with routes varying by country and local rules.|Limited production, shipping, demand, and allocations can affect which bottles a restaurant can obtain.|A list price also supports storage, glassware, staffing, service, and the business itself; there is no universal markup that explains every list.|If a wine is unavailable or above the guest’s budget, offer a comparable style at a clear price instead of turning scarcity into pressure.',
'Producer|Trade partners|Restaurant + guest','“That bottle isn’t available, but here’s a similar style within your budget.”',[
q('What can an importer do?','Bring a wine into a market','Grow every grape personally','Set every restaurant’s price','Different partners handle different parts of a bottle’s journey.'),
q('An allocation can limit…','How much a buyer can obtain','How acidic a wine tastes','How many grapes are legal','Supply and demand can influence access to particular wines.'),
q('Is restaurant pricing explained by one universal multiplier?','No','Yes','Only for imports','Costs and business choices vary.'),
q('How should you handle an unavailable bottle?','Offer a clear, suitable alternative','Invent artificial urgency','Imply the guest has missed their only chance','Helpful service respects both preference and budget.')],['br-trade','hospitality'],['br-bordeaux','br-drinkers']),
lesson('farming','Natural, organic & biodynamic',12,'technique','Three overlapping conversations, not three synonyms.',
'Organic certification follows defined rules, but wine-label categories and permitted cellar practices depend on the market; in the US, organic wine and wine made with organic grapes are different claims.|Biodynamic certification, such as Demeter, adds its own whole-farm and processing standards rather than simply borrowing the word organic.|Natural wine is a looser umbrella for low-intervention approaches, without one universal legal definition or a guaranteed taste.|Ask what the producer actually does and what is certified, and never turn these terms into promises of no sulfites, no headaches, or superior quality.',
'Organic · defined standards|Biodynamic · additional standards|Natural · check the meaning','“Are you interested in a certification, farming practices, or a particular style?”',[
q('Are these three terms interchangeable?','No','Yes','Only on white wine labels','They describe related but distinct ideas and standards.'),
q('In the US, organic wine and made with organic grapes…','Are different labeling categories','Mean exactly the same thing','Guarantee identical flavor','Read the actual claim rather than shortening it to a buzzword.'),
q('Does natural mean one universally defined style?','No','Yes, always cloudy','Yes, always skin-contact','Ask about the producer’s practices and this bottle’s character.'),
q('Which promise should you avoid?','“This cannot give anyone a headache”','“I can check the certification”','“Let’s look at the producer’s notes”','A farming or cellar term is not a personal health guarantee.')],['br-organic','br-demeter','natural'],['br-orange','br-unknown-bottle']),
lesson('champagne','Champagne beyond “Champagne”',12,'technique','The small print can become a friendly menu.',
'Grower Champagne commonly points to growers making their own wine, while houses may buy grapes; neither model automatically wins on quality.|Vintage Champagne highlights one harvest, while non-vintage blends commonly draw on several years for a house style.|Blanc de Blancs means white grapes, usually Chardonnay, and Blanc de Noirs means dark-skinned grapes such as Pinot Noir or Meunier made into white Champagne.|Dosage helps set the final balance and sweetness category, so ask about the bottle’s dryness and weight rather than treating every unfamiliar term as a higher rank.',
'Who makes it?|Which years + grapes?|What balance?','“Would you like something especially crisp, or a broader, richer style of Champagne?”',[
q('Grower Champagne automatically outranks a house wine. True?','No','Yes','Only if it is vintage','Production structure and personal preference are different from a universal ranking.'),
q('Non-vintage Champagne commonly blends…','Wines from several years','Only red and white bottled wines','Only the oldest available harvest','Blending years can support a recognizable style.'),
q('Blanc de Noirs is…','White Champagne from dark-skinned grapes','Always a red sparkling wine','Champagne without grapes','Gentle pressing can produce pale juice from dark-skinned fruit.'),
q('Dosage helps shape…','Final balance and sweetness','The vintage year','The vineyard’s location','Use it alongside the wine’s acidity and stated style.')],['br-champagne','br-growers','br-champagne-blending'],['br-vintage','br-language']),
lesson('unknown-bottle','The bottle you don’t know',12,'technique','Not knowing is a perfectly useful starting point.',
'Start with where the wine is from and its grape or blend, then use climate as a tentative clue to ripeness and freshness.|Read the producer’s information for sweetness, skin contact, oak, and other choices that could change your first guess.|When appropriate, taste and compare its body, acidity, and grip with a familiar wine, naming both a similarity and a difference.|Offer one plain-language description, check the guest’s preference and budget, and say “I’ll find out” when the bottle still has a question for you.',
'Place + grape + climate|Producer + taste|Compare + ask','“If you enjoy that familiar wine, this shares its freshness—but has a little more grip.”',[
q('What is a useful first step with an unfamiliar bottle?','Identify place and grape or blend','Invent a tasting note','Assume the bottle shape proves the style','Begin with information you can check.'),
q('Your climate guess conflicts with the producer’s notes. You…','Revise the guess','Ignore the notes','Promise both descriptions are certain','A clue is provisional; better evidence should change the prediction.'),
q('A good comparison names…','A useful similarity and a difference','Only the more famous wine’s price','A claim that both wines are identical','A familiar reference helps without erasing the new wine’s character.'),
q('What if you still do not know an answer?','Say you’ll check and follow through','Choose the most impressive guess','Avoid returning to the table','Curiosity and reliable follow-through are the skills. You already have the map.')],['labels','hospitality'],['br-language','br-other-whites']),
];
// Stable answer positions across refreshes and editorial reordering.
for(const l of backroadsLessons)for(const [i,question] of l.questions.entries()){
 const shift=([...l.id].reduce((sum,c)=>sum+c.charCodeAt(0),0)+i)%question.options.length;
 question.options=[...question.options.slice(shift),...question.options.slice(0,shift)];
 question.correct=(question.options.length-shift)%question.options.length;
}
