import type {LessonContent, Question} from './model.ts';
const q=(prompt:string,answer:string,b:string,c:string,why:string):Question=>({prompt,options:[answer,b,c],correct:0,why});
const d=(centralIdea:string,sentences:string,kind:LessonContent['visual']['kind'],labels:string,takeaway:string,questions:Question[],sources:string[]):LessonContent=>({centralIdea,subtitle:centralIdea,sentences:sentences.split('|'),visual:{kind,labels:labels.split('|')},takeaway,questions,sources});
export const content:Record<string,LessonContent>={
welcome:d('Wine starts with grapes and a little yeast.',
'Wine is grape juice transformed by fermentation: yeast consumes sugar and produces alcohol and carbon dioxide.|Place, grape variety, and cellar choices shape the result.|Humans have been doing this for thousands of years, which explains the wonderfully tangled vocabulary.|Your job is to help someone enjoy a choice, not to memorize the entire tangle.',
'process','Grapes|Yeast + time|Wine','“Tell me a wine you’ve enjoyed, and we can start there.”',[
q('Who turns sugar into alcohol?','Yeast','Oak','Grape skins alone','Yeast does that work during fermentation. Tiny colleague, impressive output.'),
q('What shapes a wine?','Place, grape, and technique','Only the price','Only the bottle age','Those three clues will be our routes through the same wine world.'),
q('A guest asks something unfamiliar. What helps?','Offer to check','Invent a confident answer','Avoid the table','Checking is professional. Fern checks his notes too.'),
q('What is your goal at the table?','Help the guest enjoy their choice','Recite every region','Sell the oldest bottle','Knowledge helps the conversation; it is not the conversation’s purpose.')],['wine']),
sweetness:d('Fruit aromas and sweetness are different clues.',
'In everyday wine language, dry means little or no noticeable sweetness.|A wine can smell of peaches or berries and still taste dry.|Off-dry means a little sweetness, while acidity can change how sweet a wine seems.|When a guest says “not fruity,” ask whether they mean sugary or strongly fruit-scented.',
'taste','AROMA · fruit scent|TASTE · sugar','“When you say fruity, do you mean sweet, or a strong fruit aroma?”',[
q('Dry usually describes…','Low perceived sweetness','Strong tannin','A lack of fruit aroma','Dry is about sweetness. Grip belongs in a different bucket.'),
q('A wine smells of peach. Must it be sweet?','No','Yes','Only if it is white','Aroma and sugar are separate. Peachy smells can accompany dry wine.'),
q('What does off-dry suggest?','A little sweetness','A faulty bottle','No acidity','It is a useful style clue, though perception varies.'),
q('“Not fruity, please.” What do you ask?','“Do you mean sweetness or aroma?”','“So, definitely red?”','“Shall I choose the cheapest?”','Clarifying their meaning prevents a confident recommendation in the wrong direction.')],['styles']),
acidity:d('Acidity is the refreshing, mouth-watering sensation.',
'Acidity makes your mouth water, rather like a squeeze of lemon.|It is different from tannin, which feels drying and grippy.|A wine can have both noticeable acidity and sweetness.|Use words such as crisp or refreshing as a starting point, then check what the guest enjoys.',
'process','Lemon-like freshness|Mouth waters|Acidity','“Do you enjoy a crisp, mouth-watering white, or something softer?”',[
q('Which sensation points toward acidity?','Mouth-watering freshness','Dry gums','A vanilla smell','Acidity encourages that mouth-watering response.'),
q('Can a wine be sweet and high in acidity?','Yes','Never','Only when sparkling','These are separate parts of the wine’s balance.'),
q('A guest wants “crisp.” Which clue helps?','Noticeable acidity','A heavy bottle','A high price','Crisp often points toward acidity, though it is still worth checking their preference.'),
q('Drying grip is usually a clue to…','Tannin','Acidity alone','The vintage number','Keeping grip and mouth-watering freshness apart makes descriptions more useful.')],['acidity']),
structure:d('Weight and grip are two separate sensations.',
'Body is a wine’s sense of weight, from light to full.|Tannin is the drying grip you might recognize from strong black tea.|A lighter-bodied red can still have noticeable tannin, and a full-bodied white need not feel grippy.|Ask about weight and grip separately instead of treating “big” as a complete description.',
 'taste','BODY · light to full|TANNIN · gentle to grippy','“Would you like a fuller wine, and are you comfortable with a little drying grip?”',[
q('Body describes…','Weight in the mouth','Sweetness alone','Bottle size','Body is the weight bucket, not the sugar bucket.'),
q('Strong black tea is a useful comparison for…','Tannin','Bubbles','Fruit aroma','The drying grip is the useful comparison, not the flavor.'),
q('Can a lighter red have firm tannin?','Yes','No','Only if it is sweet','Weight and grip can move independently.'),
q('“A big wine.” What could you clarify?','“Fuller body, firmer grip, or both?”','“You mean an older vintage?”','“So the largest bottle?”','A little translation is more useful than an assumption.')],['mouthfeel']),
labels:d('A label can introduce a grape, a place, or both.',
'Some labels lead with a grape, such as Riesling; others lead with a place, such as Bordeaux.|A region sits inside a country, and smaller named areas can sit inside that region.|Vintage means the year the grapes were harvested.|Use place and grape as clues, then check the producer’s notes for the actual style.',
 'labels','Country · France|Region · Burgundy|Grape · Chardonnay','“This name tells us where it comes from; let me check the grape and style.”',[
q('Bordeaux on a label names a…','Place','Grape','Sweetness level','Bordeaux is a region in France.'),
q('Riesling names a…','Grape','French region','Bottle size','A grape name is a starting clue, not a complete flavor promise.'),
q('Vintage tells you…','The harvest year','The bottling day','The last safe drinking date','It marks when the grapes were harvested.'),
q('Which relationship makes sense?','France → Burgundy → a local area','Burgundy contains France','Chardonnay is a country','The wine map has places within places. We only need a few useful signposts.')],['labels','burgundy']),
france:d('French place names are useful clues to wine styles.',
'French wine labels often emphasize place, reflecting long traditions and regional rules.|Bordeaux is in southwest France; Burgundy is farther east.|The Loire runs across western and central France, while Champagne lies northeast of Paris.|These places give us useful grape and technique clues, not guarantees about every bottle.',
 'regions','SW · Bordeaux|E · Burgundy|W/central · Loire|NE · Champagne','“That’s a French place name; we can use it to narrow down the style.”',[
q('Why learn a few French regions?','Labels often lead with place','All French wines taste alike','French wine must be expensive','Place names make a label easier to translate.'),
q('Bordeaux is in…','Southwest France','New Zealand','Northern Italy','A broad location is enough for this first map.'),
q('Champagne is…','Northeast of Paris','In southern Spain','A grape variety','It is a place as well as the name of its famous wine.'),
q('Does a region guarantee a precise flavor?','No; check the actual bottle','Yes, without exceptions','Only for reds','Region gives clues; producer and vintage still matter.')],['bordeaux','burgundy','loire','champagne']),
bordeaux:d('Blending combines different grapes in one wine.',
'Bordeaux is especially associated with blends rather than just one grape.|Red blends commonly include Merlot and Cabernet Sauvignon, with other permitted grapes too.|White Bordeaux often combines Sauvignon Blanc and Sémillon, and can be dry or sweet depending on the wine.|Ask which blend and style is in this bottle rather than treating Bordeaux as one flavor.',
 'vine','RED · Merlot / Cabernet|WHITE · Sauvignon / Sémillon','“This is a Bordeaux blend; would you like to know whether it feels lighter or fuller?”',[
q('A blend combines…','More than one grape or wine component','Only different bottle sizes','Wine and fruit juice by definition','Blending lets producers combine different components.'),
q('A common red Bordeaux pair is…','Merlot and Cabernet Sauvignon','Riesling and Pinot Blanc','Chardonnay and Sauvignon Blanc','These are two important red grapes in Bordeaux.'),
q('White Bordeaux may include…','Sauvignon Blanc and Sémillon','Only Merlot','Only Pinot Noir','Those are key white Bordeaux grapes.'),
q('Is all white Bordeaux dry?','No; check the style','Yes','No; it is all sweet','Both dry and sweet wines exist. A place name is not a sweetness scale.')],['bordeaux']),
burgundy:d('One familiar grape can express many places.',
'Burgundy, or Bourgogne, is in eastern France.|Its best-known white grape is Chardonnay and its best-known red is Pinot Noir, though other grapes grow here too.|Many labels highlight a village or vineyard rather than the grape name.|Learning the grape opens a door; the named place and producer help explain the particular bottle.',
 'regions','Burgundy|Chardonnay · white|Pinot Noir · red','“This white Burgundy is Chardonnay; let’s check how this producer makes it.”',[
q('The best-known white Burgundy grape is…','Chardonnay','Riesling','Merlot','Chardonnay is a useful first association, not the region’s only white grape.'),
q('The best-known red Burgundy grape is…','Pinot Noir','Cabernet Sauvignon','Sauvignon Blanc','Pinot Noir is our main red signpost here.'),
q('A village name on a label tells you about…','Origin','Guaranteed sweetness','The server’s preference','Places can be described at increasingly small scales.'),
q('Two white Burgundies must taste identical.','No','Yes','Only if both are dry','The grape may match while the place and winemaking differ.')],['burgundy']),
loire:d('One river links several different wine identities.',
'The Loire Valley spans western and central France, so it is not a single wine style.|Muscadet near the Atlantic is made from Melon, not Muscat.|Farther inland, Chenin Blanc makes dry, sweet, and sparkling wines.|Sancerre’s whites use Sauvignon Blanc, linking the Loire to bottles from much farther away.',
 'regions','Atlantic · Muscadet / Melon|Inland · Chenin Blanc|Sancerre · Sauvignon Blanc','“Sancerre’s white wine is Sauvignon Blanc; would you like a fresh, dry style?”',[
q('Muscadet is made from…','Melon','Muscat','Merlot','Similar names can be mischievous. Muscadet and Muscat are different.'),
q('Chenin Blanc can make…','Dry, sweet, and sparkling wines','Only sweet wine','Only red wine','Check the bottle’s style rather than assuming from the grape.'),
q('White Sancerre uses…','Sauvignon Blanc','Pinot Blanc','Cabernet Sauvignon','That grape connection gives us a route to Marlborough.'),
q('Does “Loire” name one style?','No, it is a broad region','Yes, always sweet','Yes, always sparkling','The long river connects several grape and style neighborhoods.')],['loire']),
champagne:d('Champagne names an origin, not every sparkling wine.',
'Champagne is a wine region in northeast France, and its name belongs to wine from that defined origin.|Its wines become sparkling through a second fermentation in the bottle.|Chardonnay, Pinot Noir, and Meunier are its principal grapes.|Other regions make excellent sparkling wines too, so offer the guest a style and price choice without using Champagne as a generic word.',
 'process','Champagne · origin|Second fermentation|Bubbles in the bottle','“Would you like Champagne specifically, or are you open to another sparkling wine?”',[
q('Champagne is first a…','Place name','Generic word for bubbles','Grape variety','The name carries an origin, not just a sparkle.'),
q('Its second fermentation happens…','In the bottle','Only in an open vat','In the vineyard','The sealed bottle retains the fermentation gas.'),
q('Which is a principal Champagne grape?','Chardonnay','Malbec','Sangiovese','Chardonnay joins Pinot Noir and Meunier among the main grapes.'),
q('A guest requests Champagne. What is useful?','Ask if they mean that origin or any sparkling wine','Assume the cheapest bubbles','Correct them sharply','A friendly clarification respects both their language and their budget.')],['champagne']),
chardonnay:d('Chardonnay is a grape, not a promise of butter or oak.',
'Chardonnay can make wines that feel lean and refreshing or broad and rounded.|Climate and ripeness influence its style, alongside choices in the cellar.|Oak can add wood-derived aromas; malolactic conversion can soften acidity and sometimes add buttery notes.|Burgundy, California, and other places grow the same grape, so ask which part of a familiar Chardonnay the guest enjoys.',
 'vine','SAME GRAPE · Chardonnay|DIFFERENT · place + making','“Is it the crispness, the round texture, or the oak that you like?”',[
q('Must Chardonnay taste oaky?','No','Yes','Only outside France','Oak is a production choice, not the grape’s definition.'),
q('What can change Chardonnay’s style?','Place and cellar choices','Only the label color','Only the glass price','This is one shared lesson reached through place, grape, or technique.'),
q('Butter notes may relate to…','Malolactic conversion','The Chardonnay name alone','Added butter','They can arise during malolactic conversion; not every wine shows them.'),
q('“Something like my Chardonnay.” Ask…','“Which part do you enjoy?”','“So, any white wine?”','“The same bottle again?”','Find the quality they want to keep before changing the bottle.')],['burgundy','malo','labels']),
sauvignon:d('Sauvignon Blanc connects places through a familiar grape.',
'Sauvignon Blanc often shows noticeable acidity and citrus, herbal, or tropical-fruit aromas.|White Sancerre in the Loire and many Marlborough wines are made from this same grape.|Their styles vary with growing conditions and winemaking; some examples use oak or blending.|Fruit aromas do not prove sweetness, so check the bottle and the guest’s meaning of “fruity.”',
 'vine','Sancerre · Sauvignon Blanc|Marlborough · Sauvignon Blanc','“Do you like the refreshing acidity, or is it the herbal or fruit aroma?”',[
q('White Sancerre and many Marlborough whites share…','Sauvignon Blanc','The same climate','Guaranteed identical flavors','The grape connects the places without making their wines identical.'),
q('A common structural clue is…','Noticeable acidity','Always firm tannin','Always high sugar','Acidity is often a useful signpost for Sauvignon Blanc.'),
q('Can Sauvignon Blanc see oak?','Yes','Never','Only when sparkling','Some producers use oak, so the grape name is not the whole story.'),
q('A tropical aroma means…','An aroma clue, not proof of sugar','The wine must be sweet','The wine comes only from the tropics','Keep aroma, sweetness, and geography in separate buckets.')],['loire','nz']),
pinot:d('Pinot Noir often offers a gentler red-wine starting point.',
'Pinot Noir is a dark-skinned grape used for red wines in Burgundy, Oregon, and many other places.|Its reds often feel lighter-bodied and less grippy than many Cabernet Sauvignon wines.|That is a tendency rather than a guarantee, because place and technique still matter.|For someone seeking a gentler red, check the actual Pinot Noir on your list before recommending it.',
 'vine','Pinot Noir · often lighter|Cabernet · often firmer','“This Pinot Noir may suit you if you prefer a lighter red with gentler grip.”',[
q('Pinot Noir is a…','Grape','Region','Barrel type','A familiar grape can travel through many regions.'),
q('Compared with many Cabernets, Pinot Noir often feels…','Lighter and less grippy','Always sweeter','Always fuller','This is a useful tendency, with plenty of variation.'),
q('Can Oregon and Burgundy both grow Pinot Noir?','Yes','No','Only for sparkling wine','Same grape, different growing conditions and choices.'),
q('Before recommending a gentle Pinot, check…','The bottle’s actual style','Only its price','Only its age','A grape generalization should support, not replace, knowing the list.')],['burgundy','oregon']),
'cabernet-merlot':d('Related grapes can contribute different kinds of structure.',
'Cabernet Sauvignon and Merlot are important Bordeaux grapes grown around the world.|Cabernet often brings firm tannin; Merlot often contributes a rounder impression, though both can make substantial wines.|Blends can combine their different qualities.|Do not translate Merlot as weak or Cabernet as automatically better; ask what weight and grip the guest wants.',
 'vine','Cabernet · often firmer|Merlot · often rounder|Blending · a balance','“Would you prefer a firmer grip or something rounder at a similar weight?”',[
q('Cabernet Sauvignon commonly contributes…','Firm tannin','Guaranteed sweetness','Only bubbles','Firm structure is a tendency, not a rule for every bottle.'),
q('Is Merlot always light?','No','Yes','Only in Bordeaux','Merlot can make substantial wines too.'),
q('Why blend these grapes?','Combine different qualities','Hide that one is always inferior','Remove all tannin','Blending is a creative choice, not an automatic sign of lower quality.'),
q('Which follow-up helps a red-wine guest?','“How much drying grip do you enjoy?”','“You must prefer Cabernet?”','“Can you name the vineyard?”','A sensation is easier to use than a test of wine knowledge.')],['bordeaux']),
riesling:d('Riesling has a sweetness range, not one sweetness setting.',
'Riesling commonly keeps noticeable acidity and can make dry through very sweet wines.|Its fruit or floral aromas do not tell you the sugar level by themselves.|Trocken on a German label means dry, while a harvest-ripeness term alone is not a reliable sweetness answer.|Check the producer’s description, then offer a style that matches the guest’s preference.',
 'taste','Dry|Off-dry|Sweet · check the bottle','“This Riesling is off-dry; would a little sweetness be welcome?”',[
q('Riesling is always sweet.','False','True','Only outside Germany','The grape covers a wide sweetness range.'),
q('Trocken on a German label means…','Dry','Sparkling','Oak-aged','It is a useful sweetness clue, not a grape name.'),
q('Floral aromas prove that a Riesling is sweet.','No','Yes','Only when chilled','Aromas and sugar are different clues.'),
q('What should you check before recommending?','The particular wine’s sweetness','Only the country','Only the bottle shape','A precise style description helps the guest more than the grape stereotype.')],['germany']),
italy:d('Italian place names need a grape-and-style translation.',
'Italy contains many distinct wine regions, so Italian wine is not one flavor family.|Chianti Classico in Tuscany is based on Sangiovese.|Barolo in Piedmont is made from Nebbiolo, a different grape with its own structure.|Translate one bottle’s place and grape into a useful style instead of treating the country as a shortcut.',
 'regions','Italy → Tuscany → Sangiovese|Italy → Piedmont → Nebbiolo','“This is a Sangiovese-based Tuscan red; let me explain its grip and freshness.”',[
q('Chianti Classico is associated with…','Sangiovese','Malbec','Sauvignon Blanc','Sangiovese is its principal grape.'),
q('Barolo is made from…','Nebbiolo','Merlot','Chardonnay','Nebbiolo is the grape; Barolo is the wine’s named origin.'),
q('Tuscany and Piedmont are…','Different regions in Italy','Grape varieties','The same appellation','The country contains many distinct wine neighborhoods.'),
q('A guest wants an Italian red. Next ask…','“Lighter or fuller, and how much grip?”','“So any Italian bottle will do?”','“The oldest one?”','Translate the broad origin into a style they actually enjoy.')],['italy','barolo']),
spain:d('Origin and aging words offer different clues.',
'Spain has many wine regions; Rioja is one of them.|Tempranillo is a key red grape in Rioja.|Words such as Crianza and Reserva describe regulated aging categories whose details depend on the region and wine type.|They are not grape names or a promise that the older category will suit every guest better.',
 'labels','Rioja · place|Tempranillo · grape|Reserva · aging category','“Would you enjoy oak influence, or would you rather keep the fruit more prominent?”',[
q('Rioja is a…','Place','Grape','Sweetness level','Origin and grape names do different jobs.'),
q('A key Rioja red grape is…','Tempranillo','Riesling','Pinot Blanc','Tempranillo is an important Rioja signpost.'),
q('Reserva tells you about…','An aging category','A grape variety','A guaranteed best choice','Its rules depend on the wine’s origin and type.'),
q('Should you always recommend the longest-aged category?','No, ask about the guest’s style','Yes','Only with seafood','Age is a clue, not a universal ranking of enjoyment.')],['rioja','rioja-aging']),
'germany-austria':d('These neighboring countries offer plenty of dry whites.',
'Germany and Austria are separate countries with many regional styles.|Germany is strongly associated with Riesling, including dry examples labeled trocken.|Austria is especially associated with Grüner Veltliner, often made dry, and also grows Riesling.|Country and grape narrow the search, but the particular label or producer confirms sweetness.',
 'regions','Germany · Riesling|Austria · Grüner Veltliner|Sweetness · check each bottle','“These are both dry options; would you like to compare their freshness and weight?”',[
q('Does German origin guarantee sweet wine?','No','Yes','Only for Riesling','Dry German wines are an important part of the picture.'),
q('Austria’s signature white grape is…','Grüner Veltliner','Malbec','Sangiovese','Grüner Veltliner is a useful Austrian starting point.'),
q('Does Austria also grow Riesling?','Yes','No','Only for sweet wine','Grapes cross borders; country and grape are separate clues.'),
q('To confirm sweetness, use…','The actual label or producer notes','The country alone','The length of the bottle','A specific wine deserves a specific answer.')],['germany','austria']),
pacific:d('A state is too large to be a flavor guarantee.',
'California and Oregon are wine-growing states on the United States’ Pacific side.|California has warm inland sites and cooler coastal influences, so its Chardonnay is not all one style.|Oregon’s Willamette Valley is especially associated with Pinot Noir.|Use the smaller region and producer’s choices to refine a recommendation rather than guessing from the state.',
 'regions','Pacific coast|California · varied sites|Oregon · Willamette / Pinot','“Do you want to keep the grape, or the texture you liked in that California wine?”',[
q('Is all California Chardonnay rich and oaky?','No','Yes','Only when young','Coastal climate and cellar choices create many styles.'),
q('Willamette Valley is in…','Oregon','California','France','It is an important Oregon Pinot Noir region.'),
q('Which gives a more useful clue?','Smaller region plus producer notes','State alone','Bottle weight','A closer look usually beats a broad stereotype.'),
q('A guest wants a change from California Chardonnay. Ask…','“Which qualities should we keep?”','“Then no more Chardonnay?”','“Shall I choose any Oregon red?”','Change one part of the experience while preserving what they enjoy.')],['california','oregon']),
southern:d('Grapes travel; their new places still matter.',
'Marlborough at the northeastern tip of New Zealand’s South Island is known for Sauvignon Blanc.|Many examples show high acidity with citrus, tropical-fruit, or herbal aromas.|Mendoza in western Argentina, near the Andes, is especially associated with Malbec, a grape with French roots.|These two stops show that a grape can travel while place and winemaking reshape its expression.',
 'flight','France|New Zealand / Argentina|Marlborough · Sauvignon / Mendoza · Malbec','“Would you like to follow a familiar grape into a different place?”',[
q('Marlborough is in…','New Zealand','Argentina','France','It sits on the northeastern South Island.'),
q('Mendoza is especially associated with…','Malbec','Pinot Blanc','Melon','Mendoza gives us a second example of grapes finding a new home.'),
q('A tropical aroma in Sauvignon Blanc proves…','Neither sweetness nor a tropical origin','That it is sweet','That it is from a tropical island','Sensory words are clues, not a passport or sugar test.'),
q('A grape moves countries. Will its wine be identical?','Not necessarily','Always','Only if the name stays the same','Growing conditions and cellar choices still matter.')],['nz','argentina']),
fermentation:d('Yeast turns grape sugar into alcohol and gas.',
'During alcoholic fermentation, yeast consumes sugar and produces alcohol and carbon dioxide.|For many still wines, the gas is allowed to escape.|Keeping fermentation gas is one way to create sparkling wine.|Oak is a separate cellar choice, not a requirement for fermentation.',
 'ferment','Sugar + yeast|Alcohol + CO₂|Still or sparkling','“Fermentation makes the alcohol; handling the gas helps determine whether there are bubbles.”',[
q('Yeast consumes…','Sugar','Glass','Tannin','Sugar is the fuel for alcoholic fermentation.'),
q('Alongside alcohol, fermentation produces…','Carbon dioxide','Oak','Grape skins','Carbon dioxide is the gas in fermentation bubbles.'),
q('For many still wines, that gas…','Escapes','Always stays trapped','Turns into tannin','Allowing it to escape is common for still-wine production.'),
q('Does fermentation require an oak barrel?','No','Yes','Only for whites','Steel and other vessels work too.')],['wine']),
oak:d('Oak is a cellar choice with a range of effects.',
'Oak vessels can be used for fermentation or maturation.|Newer oak can contribute aromas such as vanilla or toast, while older vessels usually contribute less wood flavor.|Vessel size, time, and producer choices affect the result.|Buttery notes are not proof of oak; malolactic conversion is a different process.',
 'process','Newer oak · more flavor potential|Older oak · less flavor potential','“Do you enjoy a little toast or vanilla character, or prefer less oak influence?”',[
q('Oak describes…','A cellar choice','A grape','A sweetness category','It is one of the producer’s tools.'),
q('Which often contributes more wood flavor?','Newer oak','Well-used oak','Stainless steel','Newer wood generally has more extractable flavor, with many other variables.'),
q('Butteriness proves oak aging.','False','True','Only in Chardonnay','Oak and malolactic conversion are different processes.'),
q('Two oak-aged wines must taste equally woody.','No','Yes','Only if both are red','Vessel age, size, time, and other choices change the effect.')],['oak','malo']),
malo:d('Softening acidity is different from adding oak flavor.',
'Malolactic conversion changes sharper malic acid into softer lactic acid through bacteria.|It generally lowers acidity and can produce buttery aromas, though not every example smells buttery.|It is common in reds and a style choice for many whites.|Lees contact, with spent yeast cells, is another separate choice that can influence texture.',
 'process','Malic acid|Bacteria|Softer lactic acid','“For a rounder white, I’ll check the texture as well as the oak.”',[
q('Malolactic conversion is carried out by…','Bacteria','Oak staves','A grape skin pigment','Different tiny workers from alcoholic fermentation.'),
q('Its usual acid effect is…','Softer, lower acidity','Guaranteed higher acidity','No possible change','It converts malic acid into lactic acid.'),
q('Does every wine that undergoes it smell buttery?','No','Yes','Only if red','The aroma effect depends on how the wine is made.'),
q('Lees contact means contact with…','Spent yeast cells','New oak only','Grape labels','It is a separate texture tool, not another name for malolactic conversion.')],['malo']),
sparkling:d('Different methods can lead to the same useful thing: bubbles.',
'The traditional method uses a second fermentation in the bottle, as in Champagne.|The tank method commonly uses a pressurized tank for that fermentation, as in many Proseccos.|Ancestral-method wines finish an initial fermentation in bottle, trapping its gas.|Method helps explain style, but does not by itself tell you sweetness or which wine a guest will prefer.',
 'process','Traditional · second / bottle|Tank · commonly second / tank|Ancestral · first / bottle','“Do you prefer something fruit-focused, or a style with more yeast-derived character?”',[
q('Traditional method second fermentation happens…','In the bottle','Always in a tank','In the vineyard','That bottle fermentation is the central distinction.'),
q('Many Proseccos use…','Tank method','Only traditional method','Added still red wine','A pressurized tank can retain fermentation gas.'),
q('Ancestral method captures gas from…','The initial fermentation finishing in bottle','A mandatory second fermentation','Oak maturation','That is our connection to pét-nat.'),
q('Does method alone tell you sweetness?','No','Yes','Only for Champagne','Check the actual wine’s sweetness and style.')],['sparkling']),
'skin-aging':d('Skin contact and aging are different parts of a wine’s story.',
'Contact with grape skins can add color and tannin; red wines usually ferment with dark skins.|White grapes fermented with skins can make amber or orange wine, without any oranges.|After fermentation, maturation can change aroma and texture, but it does not mean more skin contact.|Neither deeper color nor greater age automatically means better wine or more sweetness.',
 'color','Skins · color + grip|Maturation · change over time|Color ≠ sweetness','“This amber wine has skin-derived grip; would that texture appeal to you?”',[
q('Most red-wine color comes from…','Grape skins','The cork','Added berries','Contact extracts color from dark skins.'),
q('Orange wine is generally…','White grapes with skin contact','Orange juice fermented','A mandatory red-white blend','Amber is a color description here, not a fruit ingredient.'),
q('Does maturation mean more skin contact?','No','Yes','Only in a barrel','Skin contact and later aging are separate decisions.'),
q('Older wine is always better.','False','True','Only for reds','Some wines are best young, and preference matters.')],['burgundy','skin']),
terroir:d('Place is a set of growing conditions, not a magic flavor.',
'Terroir is a way to discuss how a site’s conditions and human practices shape wine.|Climate, slope, soil, and water availability can affect vine growth and ripening.|A stone in the vineyard does not mean the wine literally contains that stone’s flavor.|Farming and cellar choices still matter, so use terroir to invite curiosity rather than claim certainty.',
 'regions','Climate + site|Farming choices|Grapes → wine','“This cooler site is one clue to the wine’s freshness; the producer’s choices matter too.”',[
q('Terroir helps describe…','Site conditions and human practices','Only the label design','A guaranteed rock flavor','It is a useful way to connect place with wine.'),
q('Which can influence ripening?','Climate and water availability','The restaurant’s glassware','The bottle price','Growing conditions affect how grapes develop.'),
q('A rocky vineyard guarantees a rock taste.','False','True','Only for whites','Avoid turning a metaphor into a literal ingredient claim.'),
q('Does place erase the effect of winemaking?','No','Yes','Only for expensive wine','Place and technique belong in the same conversation.')],['terroir']),
organic:d('Farming terms tell you about practices, not guaranteed taste.',
'Organic certification concerns specified farming and production rules that differ by certification and location.|Biodynamic farming includes organic principles plus additional preparations and a whole-farm approach.|Regenerative approaches emphasize outcomes such as soil health, but standards and certification schemes vary.|Check the specific certification and producer practices; none of these words guarantees taste, quality, or a health benefit.',
 'labels','Organic · specified rules|Biodynamic · additional practices|Regenerative · check the scheme','“I’ll check which practices or certification this producer actually uses.”',[
q('What is most useful when a guest asks about organic wine?','Check the specific certification','Assume every label uses identical rules','Promise a health benefit','The term needs the context of a scheme and location.'),
q('Biodynamic farming includes…','Additional practices beyond organic principles','No farming rules at all','A guaranteed flavor','Describe the practices without promising an outcome in the glass.'),
q('Does regenerative always mean the same certified standard?','No','Yes','Only on expensive bottles','Ask which practices and scheme the claim refers to.'),
q('Can these terms guarantee the guest will like the wine?','No','Yes','Only if all three appear','Production information and personal enjoyment are different questions.')],['organic','biodynamic','regenerative']),
natural:d('“Natural” needs a follow-up question.',
'Natural and low-intervention generally signal an intention to add or remove less during winemaking.|There is no single worldwide standard covering every use of these words, though some groups have their own rules.|The words alone do not prove certification, absence of sulfites, a cloudy appearance, or a particular flavor.|Ask which practice or style matters to the guest, then check the producer’s information.',
 'process','A broad term|A specific question|A checked answer','“Are you looking for a farming practice, fewer additions, or a particular style?”',[
q('Does natural have one worldwide standard?','No','Yes','Only for red wine','Some groups define it; not every use of the word follows the same rules.'),
q('Does natural guarantee no sulfites?','No','Yes','Only if cloudy','Do not turn a broad label into a precise composition claim.'),
q('A guest requests natural wine. Ask…','“Which practices or style matter to you?”','“So you want a funky wine?”','“Only the cloudy ones?”','Practices and sensory preferences are separate.'),
q('Is natural automatically better than conventional?','No; assess the wine and the guest’s needs','Always','Only when expensive','Avoid teams and slogans. Useful information is enough.')],['natural']),
petnat:d('Pét-nat catches the first fermentation’s bubbles.',
'Pét-nat is short for pétillant naturel and commonly refers to ancestral-method sparkling wine.|The wine is bottled before its initial fermentation has finished, retaining carbon dioxide.|Some bottles keep sediment while others have it removed; appearance and pressure vary.|The method does not certify farming practices or promise sweetness, so check this bottle before describing it.',
 'ferment','Initial fermentation|Bottle before it finishes|Retain the fizz','“This pét-nat uses the first fermentation for its bubbles; I’ll check its sweetness and sediment.”',[
q('Pét-nat commonly refers to…','Ancestral-method sparkling wine','Still orange wine','A grape variety','It names a style and method connection, not a grape.'),
q('The bubbles come from…','The first fermentation finishing in bottle','Mandatory second fermentation','Oak maturation','That is the central difference from traditional method.'),
q('Must every pét-nat look cloudy?','No','Yes','Only if white','Some producers remove the sediment.'),
q('Does pét-nat prove organic certification?','No','Yes','Only with a crown cap','Method, farming, and certification are separate questions.')],['sparkling']),
flaws:d('Take a guest’s concern seriously before debating the wine.',
'Unfamiliar aromas can reflect a style, a bottle problem, or a person’s preferences.|Musty, damp-cardboard aromas can suggest cork taint, while unexpected oxidation can dull fruit.|Cloudiness or sediment alone does not prove a fault, and acceptable character varies with the intended style.|If a guest is unhappy, listen and check with the wine lead under the restaurant’s replacement policy.',
 'process','Listen|Check bottle + style|Resolve kindly','“Thanks for telling me; I’ll have this checked and help you find a comfortable next step.”',[
q('A guest says the bottle seems wrong. First…','Listen and offer to check','Defend the producer','Tell them it is fashionable','Hospitality comes before an argument over vocabulary.'),
q('Musty, damp-cardboard aromas can suggest…','Cork taint','Extra freshness','Guaranteed age-worthiness','That is a possible clue, not a diagnosis from one word.'),
q('Does sediment alone prove a fault?','No','Yes','Only in red wine','Sediment can occur without the wine being faulty.'),
q('Who helps resolve a questionable bottle?','The wine lead and restaurant policy','Only the label','A claim that funk is always good','Check the wine and follow a consistent service process.')],['faults']),
'acid-salt':d('Food can change how the same wine seems.',
'Acidic food can make a wine seem less acidic, so a wine with enough freshness often works well.|Salt can soften the impression of bitterness and acidity in wine.|These are common sensory tendencies, not a rule about everyone’s palate.|Try the wine before and after a bite, and ask which version the guest enjoys.',
 'process','Wine alone|A salty or acidic bite|Notice the difference','“With that lemony dish, would you enjoy a wine with a little extra freshness?”',[
q('Acidic food often makes wine seem…','Less acidic','Always sweeter by adding sugar','More tannic in every case','Perception changes even though the liquid is the same.'),
q('Salt can soften the impression of…','Bitterness and acidity','Bottle age','The grape name','This is a sensory tendency, not a chemical change to the bottle.'),
q('The useful mini-experiment is…','Taste before and after a bite','Read only the label','Choose by color alone','A small comparison makes the interaction easier to notice.'),
q('Must everyone enjoy the same pairing?','No','Yes','Only with salty food','The guest’s preference is part of the pairing.')],['pairing']),
richness:d('You can refresh a rich dish or echo its texture.',
'A rich or creamy dish can welcome a wine with refreshing acidity.|A rounder wine can instead echo some of the food’s weight.|Sauce and preparation may matter more than whether the main ingredient is meat or fish.|Ask whether the guest wants contrast or a similarly rounded experience, then check the bottle.',
 'taste','Contrast · refreshing acidity|Echo · rounder texture','“Would you like something refreshing alongside the sauce, or a wine with a similar roundness?”',[
q('A refreshing contrast to a creamy dish may come from…','Acidity','Bottle weight','More age by itself','Acidity can give a useful sense of refreshment.'),
q('A rounder wine can…','Echo the dish’s weight','Guarantee a better pairing','Remove the sauce’s fat','Echoing and contrasting are both reasonable approaches.'),
q('What detail should you ask about?','The sauce and preparation','Only the protein name','The plate color','The whole dish matters, not just its headline ingredient.'),
q('Which approach should you choose?','The one that suits the guest','Always contrast','Always match the weight exactly','There is room for preference, not one compulsory answer.')],['pairing','mouthfeel']),
spice:d('Chilli heat changes the recommendation conversation.',
'Chilli heat can make alcohol feel more burning and some wines seem harsher.|A little sweetness and lower alcohol can be useful when the guest wants to soften that impression.|Not every spiced dish is hot, and some guests enjoy the heat.|Ask how hot the dish is and whether the guest welcomes a little sweetness before suggesting off-dry wine.',
 'taste','Chilli heat|Alcohol · may feel hotter|A little sweetness · an option','“How much heat do you enjoy, and would a touch of sweetness be welcome?”',[
q('Chilli can make alcohol feel…','More burning','Always invisible','Like tannin has vanished','Consider alcohol as well as sweetness.'),
q('A possible gentle option is…','Lower alcohol with a little sweetness','The highest alcohol available','Any red because it is red','That can help, if the guest likes the style.'),
q('Does a spiced dish always have chilli heat?','No','Yes','Only in summer','Aromatic spices and chilli heat are not the same thing.'),
q('Before choosing off-dry Riesling, ask…','“Would a little sweetness suit you?”','“You dislike dry wine, right?”','“Shall I bring the sweetest bottle?”','A useful suggestion still needs the guest’s preference.')],['spice']),
seafood:d('Preparation and preference matter more than a color rule.',
'Oysters with lemon often suit fresh, dry whites or sparkling wines, if the guest enjoys those styles.|Creamy seafood may invite a rounder wine or a refreshing contrast.|Grilled or sauced fish can change the balance again, and some guests may prefer a lighter red.|Ask about preparation, sauce, and preferred style instead of insisting that fish always needs white wine.',
 'process','Seafood|Sauce + preparation|Guest’s preferred style','“Are you having lemon or a richer sauce, and would you prefer still or sparkling?”',[
q('For oysters, a useful starting question is…','“Still or sparkling, and what price range?”','“You know Muscadet, right?”','“Only Champagne will work, yes?”','Help the guest choose without giving them homework.'),
q('A creamy sauce can change…','Which texture or contrast suits the dish','The wine’s grape','The harvest year','Pair with the whole dish.'),
q('Must fish always have white wine?','No','Yes','Only at dinner','Preparation and preference leave room for other choices.'),
q('A good recommendation accounts for…','Food and the guest’s preferences','The protein alone','The most famous region','Both the plate and the person belong in the decision.')],['pairing','loire']),
preferences:d('Translate a preference before naming a bottle.',
'Begin with a familiar wine or a plain-language preference, such as refreshing or rounded.|Clarify vague words by asking one useful follow-up, then listen.|Ask about budget discreetly and offer one or two options with a clear difference.|Check unknown details with a colleague instead of filling the silence with a confident guess.',
 'process','Ask|Listen|Offer two useful choices','“What do you like about that wine, and what price range would feel comfortable?”',[
q('A helpful opening is…','“What do you usually enjoy?”','“How much wine do you know?”','“Would you like the most expensive?”','Start with their experience, not an exam.'),
q('The guest says smooth. What next?','Clarify whether they mean less grip or rounder texture','Assume sweet','Assume old','A broad word can point to different sensations.'),
q('How should you treat a modest budget?','With the same care as any budget','As something to correct','As a reason not to recommend','Respecting comfort is part of good service.'),
q('How many initial choices are useful?','One or two, with a clear difference','The entire list','One without explanation','Keep the decision manageable.')],['hospitality']),
'floor-chardonnay':d('Find what the guest wants to keep while changing the bottle.',
'A guest says, “I usually drink California Chardonnay but want something different.”|Ask whether they like the refreshing acidity, round texture, oak, or another feature.|Confirm budget and whether they want to keep the grape or explore a new one.|Offer two checked options that preserve their chosen feature, explaining one useful difference.',
 'process','What should stay?|What can change?|Two checked options','“What do you most enjoy about that Chardonnay, and how adventurous are you feeling?”',[
q('What is your first useful response?','“Which qualities do you enjoy?”','“You need Chablis.”','“Let’s avoid Chardonnay entirely.”','A destination comes after understanding what they want to keep.'),
q('They say “round, but less oak.” What do you check?','Texture and oak separately','Only the country','Whether the bottle is heavy','Roundness and oak are not the same feature.'),
q('They want to keep Chardonnay. Can Burgundy be considered?','Yes, if the particular style and price fit','No, it is a different grape','Yes, every bottle will fit','Burgundy links back to Chardonnay, but the bottle still needs checking.'),
q('Before presenting two options, confirm…','Their comfortable price range','That they know the producers','That they accept the most expensive','Two relevant choices should also respect budget.')],['burgundy','malo','hospitality']),
'floor-sauvignon':d('Translate “fruity” without correcting the guest.',
'A guest says, “I like Sauvignon Blanc but don’t want anything too fruity.”|Ask whether fruity means sweet or strongly scented, because people use the word differently.|If they mean less intense fruit aroma, look for a more restrained bottle rather than merely a dry one.|If they mean less sugar, confirm dryness in the producer notes and keep their budget in view.',
 'process','“Fruity”|Sweetness or aroma?|Check the bottle','“Do you mean less sweetness, or a quieter fruit aroma?”',[
q('What do you clarify first?','Their meaning of fruity','Their knowledge of France','Whether they really like wine','Their vocabulary is useful information, not an error to punish.'),
q('They mean “not sweet.” What do you check?','The wine’s dryness','Only its aroma intensity','Only its color','That answer belongs in the sugar bucket.'),
q('They mean “less tropical perfume.” What helps?','Compare actual aroma descriptions','Choose any dry bottle','Assume all Sancerre is identical','Dryness alone does not answer an aroma request.'),
q('How do you describe your suggestion?','“This is a more restrained example on our list.”','“All wines from here taste the same.”','“Your usual wine is wrong.”','Stay specific and avoid judging what they enjoy.')],['nz','loire','hospitality']),
'floor-oysters':d('Reduce uncertainty with a small, welcoming choice.',
'A table says, “We don’t know wine; we’re having oysters.”|Reassure them and ask whether still or sparkling sounds appealing.|Check their budget and condiments before offering two suitable choices.|Explain the difference in everyday terms, such as freshness or bubbles, rather than asking them to recognize appellations.',
 'process','Still or sparkling?|Budget + condiments|A simple choice','“No problem at all—would still or sparkling sound good, and what price range should I work within?”',[
q('A welcoming first response is…','“Happy to help; still or sparkling?”','“You must have Champagne.”','“Can you name a region?”','Give them an easy choice rather than a test.'),
q('Why ask about lemon or sauce?','It can change the pairing','It identifies the vintage','It removes the need to ask budget','Preparation adds useful context.'),
q('They want dry, still, and modestly priced. What next?','Check two fitting bottles on the list','Choose the best-known Champagne','Promise any Muscadet is in budget','Fit the actual list to their needs.'),
q('Which explanation helps?','“This one is a little lighter; this has more texture.”','A long list of soil types','“It is objectively the best.”','A useful difference makes the decision easier.')],['pairing','hospitality']),
'floor-caymus':d('A familiar brand is a conversation starter, not a verdict.',
'A guest says, “I usually drink Caymus.”|Ask which bottle they mean and what they like about it, without judging their preference.|They might mean ripe fruit, round texture, oak, familiarity, or something else; do not infer all of that from the name.|Confirm budget and offer a similar or contrasting option only after you understand what should stay familiar.',
 'process','Which bottle?|What do you enjoy?|Familiar or a little different?','“Which Caymus do you enjoy, and what about it would you like to keep tonight?”',[
q('What is the best first follow-up?','“Which bottle, and what do you like about it?”','“Then you only like sweet wine.”','“You should drink something more serious.”','A brand does not give permission to stereotype a guest.'),
q('They say “rich fruit and gentle grip.” Focus on…','Those sensations in the actual alternatives','Only finding the same country','Choosing the firmest tannins','Translate the description into useful bottle choices.'),
q('They are open to a change. Ask…','“How far from familiar would you like to go?”','“So anything is fine?”','“Can I double the budget?”','Curiosity has a comfort level too.'),
q('A good recommendation should…','Respect their taste and price range','Teach them their favorite is wrong','Skip the follow-up to name Bordeaux','The goal is a good evening, not winning an argument.')],['hospitality']),
'floor-mixed':d('A shared table does not always need a single bottle.',
'One guest wants a light white, another wants a full red, and the table is sharing several dishes.|Ask whether they want one shared bottle or would prefer separate glasses.|Confirm the budget, then offer a workable choice without pretending one wine must be perfect for everyone.|If a guest questions a bottle, listen and follow the restaurant’s checking and replacement process.',
 'process','One bottle or glasses?|Check preferences + budget|Agree, then serve','“Would two different glasses make everyone happier than finding one compromise bottle?”',[
q('What should you clarify first?','Shared bottle or separate glasses','Who knows the most wine','Which guest should give in','The format of the order can solve the problem.'),
q('They choose separate glasses. What next?','Match each preference within the budget','Still insist on one bottle','Choose two expensive wines','The solution should fit the people and the price range.'),
q('They prefer one bottle. How do you frame it?','A discussed compromise, with a clear style','A guaranteed perfect pairing for everything','A decision made without asking','Agreement matters more than an impossible promise.'),
q('Someone says the wine smells wrong. You…','Thank them and have it checked','Tell them to get used to it','Call it natural without checking','A calm, helpful response is the final skill, not a trivia answer.')],['hospitality','faults']),
};
// Deterministic option rotation keeps answer position varied without changing on reload.
Object.entries(content).forEach(([id,lesson])=>lesson.questions.forEach((question,qi)=>{
 const shift=([ ...id ].reduce((sum,c)=>sum+c.charCodeAt(0),0)+qi)%question.options.length;
 question.options=[...question.options.slice(shift),...question.options.slice(0,shift)];
 question.correct=(question.options.length-shift)%question.options.length;
}));
