import type {Axis, LessonNode} from './model.ts';
export const chapters=[
 {id:1,title:'Getting oriented',description:'A few useful mental buckets.'},
 {id:2,title:'France: the Rosetta Stone',description:'Places that help the wine world make sense.'},
 {id:3,title:'Follow the grape',description:'Familiar grapes, different expressions.'},
 {id:4,title:'The wider wine world',description:'Grapes and traditions on the move.'},
 {id:5,title:'How wine happens',description:'Small choices, noticeable differences.'},
 {id:6,title:'The new wine world',description:'Useful language, without taking sides.'},
 {id:7,title:'Wine at the table',description:'Listen to the food and the people.'},
 {id:8,title:'The floor',description:'Five conversations, one thoughtful server.'},
];
const n=(id:string,title:string,chapter:number,axis:Axis,secondaryConnections:Axis[],all:string[],any:string[],relatedLessons:string[],tastings:number[]):LessonNode=>({id,title,chapter,axis,secondaryConnections,prerequisites:{all,any},relatedLessons,tastingConnections:tastings.map(i=>`tasting-${i}`),kind:chapter===8?'scenario':'lesson',revision:2});
// Prerequisites gate learning. Related edges navigate the same records and may be reciprocal.
// all = every item; any = at least one item (an empty list imposes no extra gate).
export const graph:LessonNode[]=[
 n('welcome','Wine, without the worry',1,'technique',['place','grape'],[],[],['sweetness','fermentation'],[1]),
 n('sweetness','Dry is not the opposite of fruity',1,'grape',['technique'],['welcome'],[],['acidity','riesling'],[1]),
 n('acidity','Meet the mouth-watering bit',1,'grape',['place'],['sweetness'],[],['structure','acid-salt'],[1]),
 n('structure','Weight and grip',1,'grape',['technique'],['acidity'],[],['labels','pinot','cabernet-merlot'],[1]),
 n('labels','Read the bottle, not minds',1,'place',['grape'],['structure'],[],['france','preferences'],[1]),
 n('france','France 101',2,'place',['grape','technique'],['labels'],[],['bordeaux','burgundy','chardonnay','fermentation'],[2]),
 n('bordeaux','Bordeaux: a team of grapes',2,'place',['grape'],['france'],[],['cabernet-merlot','sauvignon'],[2]),
 n('burgundy','Burgundy: place under a magnifying glass',2,'place',['grape','technique'],['france'],[],['chardonnay','pinot','terroir'],[2]),
 n('loire','The Loire: follow the river',2,'place',['grape'],['france'],[],['sauvignon','riesling','seafood'],[2]),
 n('champagne','Champagne is a place',2,'place',['technique','grape'],['france'],[],['sparkling','chardonnay'],[2,5]),
 n('chardonnay','Chardonnay: one grape, many outfits',3,'grape',['place','technique'],['france'],[],['burgundy','oak','malo','pacific'],[3,5]),
 n('sauvignon','Sauvignon Blanc: familiar freshness',3,'grape',['place'],['france'],[],['loire','southern','riesling'],[1,3]),
 n('pinot','Meet Pinot Noir',3,'grape',['place','technique'],['france'],[],['burgundy','pacific','skin-aging'],[3]),
 n('cabernet-merlot','Cabernet and Merlot: relatives at the table',3,'grape',['place'],['france'],['bordeaux','pinot'],['bordeaux','spain','southern'],[3,8]),
 n('riesling','Riesling: ask about sweetness',3,'grape',['place','technique'],['france'],['loire','sauvignon'],['germany-austria','spice','sweetness'],[1,3,7]),
 n('italy','Italy: ask where, then what',4,'place',['grape'],['france'],['burgundy','pinot'],['spain','acid-salt'],[4]),
 n('spain','Spain: grape plus time',4,'place',['grape','technique'],['france'],['bordeaux','cabernet-merlot'],['oak','italy'],[4]),
 n('germany-austria','Germany & Austria: dry is an option',4,'place',['grape'],['france'],['loire','riesling'],['riesling','spice'],[4]),
 n('pacific','California & Oregon: look closer',4,'place',['grape','technique'],['france'],['chardonnay','pinot'],['chardonnay','pinot','terroir'],[4]),
 n('southern','Southern Hemisphere: two useful stops',4,'place',['grape'],['france'],['sauvignon','cabernet-merlot'],['sauvignon','cabernet-merlot','terroir'],[4]),
 n('fermentation','The tiny work of yeast',5,'technique',['grape'],['france'],[],['oak','sparkling','natural'],[5]),
 n('oak','Oak: seasoning, not a grape',5,'technique',['grape','place'],['fermentation'],[],['chardonnay','malo','spain'],[5]),
 n('malo','Texture: the softer side',5,'technique',['grape'],['fermentation'],['chardonnay','oak'],['chardonnay','richness'],[5]),
 n('sparkling','Three routes to bubbles',5,'technique',['place'],['france'],['champagne','fermentation'],['champagne','petnat','seafood'],[5,6]),
 n('skin-aging','Skin contact and the passage of time',5,'technique',['grape'],['france'],['fermentation','pinot'],['pinot','flaws','natural'],[5,6]),
 n('terroir','Terroir: a place and its people',6,'place',['technique','grape'],['france'],['burgundy','pacific','southern'],['organic','burgundy'],[6]),
 n('organic','Farming words, useful questions',6,'technique',['place'],['terroir'],[],['natural','terroir'],[6]),
 n('natural','Natural: ask what was done',6,'technique',['place'],['france'],['organic','fermentation'],['organic','petnat','flaws'],[6]),
 n('petnat','Pét-nat: catch the first fizz',6,'technique',['place'],['sparkling'],['natural','fermentation'],['sparkling','flaws'],[6]),
 n('flaws','Funk, faults, and a helpful response',6,'technique',['grape'],['france'],['natural','skin-aging'],['natural','petnat','floor-mixed'],[6,8]),
 n('acid-salt','Acid, salt, and the next bite',7,'technique',['grape'],['acidity'],['loire','sauvignon'],['seafood','italy','richness'],[7]),
 n('richness','Rich food: refresh or echo',7,'technique',['grape'],['structure'],['chardonnay','malo'],['malo','acid-salt','floor-chardonnay'],[7]),
 n('spice','Spice: ask how much heat',7,'technique',['grape'],['sweetness'],['riesling','germany-austria'],['riesling','preferences'],[7]),
 n('seafood','Seafood: the preparation matters',7,'technique',['place','grape'],['acid-salt'],['loire','sparkling'],['loire','richness','floor-oysters'],[7]),
 n('preferences','Find their kind of wine',7,'grape',['place','technique'],['labels','structure'],['acid-salt','richness','spice','seafood'],['floor-chardonnay','floor-sauvignon','floor-caymus'],[7,8]),
 n('floor-chardonnay','“Chardonnay, but something different”',8,'grape',['place','technique'],['preferences','chardonnay'],[],['malo','richness','floor-mixed'],[8]),
 n('floor-sauvignon','“Sauvignon, but not too fruity”',8,'grape',['place'],['preferences','sauvignon'],[],['sweetness','loire','floor-mixed'],[8]),
 n('floor-oysters','“We don’t know wine. We have oysters.”',8,'place',['grape','technique'],['preferences','seafood'],[],['loire','sparkling','floor-mixed'],[8]),
 n('floor-caymus','“I usually drink Caymus”',8,'grape',['place'],['preferences','cabernet-merlot'],[],['bordeaux','oak','floor-mixed'],[8]),
 n('floor-mixed','One table, several different wishes',8,'technique',['grape','place'],['preferences'],['floor-chardonnay','floor-sauvignon','floor-oysters','floor-caymus'],['preferences','flaws','floor-oysters'],[8]),
];
export const paths=[
 {axis:'place' as Axis,title:'Follow a place',label:'PLACE',text:'Travel by region, then follow the connections.',entry:'bordeaux'},
 {axis:'grape' as Axis,title:'Follow a grape',label:'GRAPE',text:'Meet a grape, then find it in other places.',entry:'chardonnay'},
 {axis:'technique' as Axis,title:'Follow the making',label:'TECHNIQUE',text:'Follow a cellar choice into the glass.',entry:'fermentation'},
];
