import {backroadsSources} from './backroads-sources.ts';
// Editorial reference ledger, reviewed 2026-09-29. Hospitality scenarios are original.
export const sources:Record<string,{title:string;url:string}>={
 ...backroadsSources,
 wine:{title:'WSET — What is wine?',url:'https://www.wsetglobal.com/knowledge-centre/blog/2021/december/14/what-is-wine'},
 styles:{title:'WSET — Wine types and styles',url:'https://www.wsetglobal.com/knowledge-centre/blog/2023/october/03/how-many-wine-types-and-styles-are-there'},
 acidity:{title:'WSET — Understanding acidity',url:'https://www.wsetglobal.com/knowledge-centre/blog/2026/understanding-acidity-in-wine'},
 mouthfeel:{title:'WSET — What is mouthfeel?',url:'https://www.wsetglobal.com/knowledge-centre/blog/2026/the-secret-language-of-wine-what-is-mouthfeel'},
 labels:{title:'WSET — How to find a wine you like',url:'https://www.wsetglobal.com/knowledge-centre/blog/2025/how-to-find-a-wine-youll-like'},
 bordeaux:{title:'Bordeaux Wine Council — Grape varieties',url:'https://www.bordeaux.com/en/grape-varieties/'},
 burgundy:{title:'Bourgogne Wine Board — Pinot Noir and Chardonnay',url:'https://www.bourgogne-wines.com/wine-and-terroir/our-grape-varietals-our-colors/pinot-noir-and-chardonnay-the-bourgogne-region-s-two-noble-grape-varietals%2C2475%2C9265.html'},
 loire:{title:'InterLoire — Grape varieties',url:'https://www.vinsdeloire.fr/fr/cepages?page=0'},
 champagne:{title:'Comité Champagne — Bottling and second fermentation',url:'https://www.champagne.fr/en/about-champagne/how-champagne-is-made/bottling-and-second-fermentation'},
 nz:{title:'New Zealand Winegrowers — Marlborough',url:'https://www.nzwine.com/en/regions/marlborough'},
 germany:{title:'German Wines USA — Dry German Riesling',url:'https://germanwineusa.com/5-to-try-talkin-trocken-dry-german-riesling/'},
 austria:{title:'Austrian Wine — Grape varieties',url:'https://www.austrianwine.com/fileadmin/user_upload/PDF/Broschueren/Rebsortenbroschuere_2019_EN.pdf'},
 italy:{title:'Chianti Classico Consortium — Wine characteristics',url:'https://www.chianticlassico.com/en/wine/characteristics/'},
 barolo:{title:'Langhe Wine Consortium — Barolo production specification',url:'https://www.langhevini.it/wp-content/uploads/2019/05/DOCG-Barolo.pdf'},
 rioja:{title:'Rioja Wine Council — Tempranillo',url:'https://riojawine.com/en-us/the-designation/grape-varieties/tempranillo/'},
 'rioja-aging':{title:'Rioja Wine Council — Aging categories',url:'https://riojawine.com/en-gb/blog/classification-of-rioja-wines-according-to-their-ageing/'},
 california:{title:'California Wine Institute — Bay Area wine region',url:'https://discovercaliforniawines.com/blog/get-to-know-the-san-francisco-bay-area-wine-region/'},
 oregon:{title:'Oregon Wine Board — Wine varieties',url:'https://www.oregonwine.org/discover/oregon-wine-varieties/'},
 argentina:{title:'Wines of Argentina — Malbec, terroir and trends',url:'https://api.winesofargentina.org/uploads/2021/11/7lxka1Q7Z3_Argentina_on_the_Couch._Malbec%2C_Terroir_and_Other_Trends_-_Report.pdf'},
 oak:{title:'WSET — Oak and style choices',url:'https://www.wsetglobal.com/knowledge-centre/blog/2025/how-to-find-a-wine-youll-like'},
 malo:{title:'WSET — Level 2 teaching plan, malolactic conversion and lees',url:'https://www.wsetglobal.com/media/13022/wset_l2wines_sessionplans_en_may2023_issue2.pdf'},
 sparkling:{title:'WSET — Sparkling wine production methods',url:'https://www.wsetglobal.com/knowledge-centre/blog/2026/a-guide-to-sparkling-wine-production-methods-and-regional-styles'},
 skin:{title:'WSET — Skin-contact white wines',url:'https://www.wsetglobal.com/knowledge-centre/blog/2026/what-is-orange-wine-understanding-skin-contact-white-wines'},
 terroir:{title:'OIV — Definition of vitivinicultural terroir',url:'https://www.oiv.int/node/3362'},
 organic:{title:'USDA — Organic market labeling, including wine',url:'https://www.ams.usda.gov/services/organic-certification/international-trade/labeling-requirements-US-organic-market'},
 biodynamic:{title:'Demeter USA — Farm and processing standards',url:'https://demeter-usa.org/demeter-biodynamic-farm-and-processing-standards/'},
 regenerative:{title:'Regenerative Organic Alliance — Soil health framework guidance',url:'https://regenorganic.org/wp-content/uploads/2023/03/Framework-Guidance-SoilHealth-LandMgmt.pdf'},
 natural:{title:'WSET — What is natural wine? (terminology only; not its value judgments)',url:'https://www.wsetglobal.com/knowledge-centre/blog/2023/january/13/what-is-natural-wine'},
 faults:{title:'Australian Wine Research Institute — Flavours, faults and taints',url:'https://www.awri.com.au/industry_support/winemaking_resources/sensory_assessment/recognition-of-wine-faults-and-taints/wine_faults/'},
 pairing:{title:'WSET — Food and wine interactions',url:'https://www.wsetglobal.com/knowledge-centre/blog/2023/july/13/four-rules-to-masterful-food-and-wine-pairing'},
 spice:{title:'WSET — Pairing drinks with spice',url:'https://www.wsetglobal.com/knowledge-centre/blog/2026/how-to-pair-drinks-with-spice'},
 hospitality:{title:'Original hospitality scenarios — restaurant wine-lead review required',url:''},
};
