import type {Tasting} from './model.ts';
export const tastings:Tasting[]=[
{id:'tasting-1',number:1,title:'Same color. Different stories.',axis:'grape',wines:['Riesling','Bordeaux Blanc','Marlborough Sauvignon Blanc','Pinot Blanc'],concept:'Keep aroma, sweetness, acidity, and body in separate buckets.',prompts:['Compare Riesling vs Bordeaux Blanc: what changes in sweetness and weight?','Compare Marlborough Sauvignon Blanc vs Pinot Blanc: what changes in aroma and freshness?'],preparation:'Choose a Riesling with known sweetness and a dry Bordeaux Blanc; verify the style of both other whites. Keep the requested pairs together.',relatedLessons:['welcome','sweetness','acidity','structure','labels','riesling','sauvignon','bordeaux']},
{id:'tasting-2',number:2,title:'A place name, a grape connection.',axis:'place',wines:['White Burgundy / Chardonnay','White Sancerre / Sauvignon Blanc','Dry white Bordeaux blend'],concept:'Translate three French place names into grapes and useful style descriptions.',prompts:['Which grape or blend sits behind each place name?','Compare freshness and weight without assuming that place guarantees flavor.'],preparation:'Choose three dry whites and use producer notes to explain differences in oak, blending, and ripeness.',relatedLessons:['france','bordeaux','burgundy','loire','chardonnay','sauvignon']},
{id:'tasting-3',number:3,title:'Three red grapes, three kinds of grip.',axis:'grape',wines:['Pinot Noir','Merlot-led red','Cabernet Sauvignon-led red'],concept:'Separate weight from tannin rather than ranking wines by power.',prompts:['Which feels lighter, and which has firmer grip?','Describe one difference that would help a guest choose.'],preparation:'Select contrasting, sound examples; blends are fine when clearly labeled. Do not promise a fixed ranking before tasting.',relatedLessons:['structure','pinot','cabernet-merlot','bordeaux','preferences']},
{id:'tasting-4',number:4,title:'A grape takes a trip.',axis:'place',wines:['Loire Sauvignon Blanc','Marlborough Sauvignon Blanc','French Malbec','Mendoza Malbec'],concept:'Compare the same grape across places without turning countries into stereotypes.',prompts:['Compare the two Sauvignon Blancs, then the two Malbecs.','Which differences could also come from producer choices rather than geography?'],preparation:'Use two to four wines: one matched grape pair is enough. Cahors can supply the French Malbec example; verify the blend.',relatedLessons:['southern','sauvignon','pacific','italy','spain','germany-austria','terroir']},
{id:'tasting-5',number:5,title:'The cellar leaves a signature.',axis:'technique',wines:['Chardonnay with little oak influence','Oak-influenced Chardonnay','Traditional-method sparkling wine','Tank-method sparkling wine'],concept:'Use producer information to connect cellar choices with sensory differences.',prompts:['Compare the Chardonnays; keep oak aromas separate from buttery or rounded impressions.','Compare the sparkling pair; discuss method without ranking the wines.'],preparation:'Use two to four wines and confirm oak, malolactic, and sparkling-method details. Different wines do not isolate a single variable perfectly.',relatedLessons:['fermentation','oak','malo','sparkling','skin-aging','chardonnay','champagne']},
{id:'tasting-6',number:6,title:'Method, label, and what is in the glass.',axis:'technique',wines:['Pét-nat / ancestral-method sparkling','Traditional-method sparkling','Skin-contact white','White made with little skin contact'],concept:'Separate method and farming claims from taste, cloudiness, and quality judgments.',prompts:['Compare the sparkling pair or the two whites using verified production notes.','What can the label establish, and what requires asking the producer?'],preparation:'Choose two to four sound wines. Include specific farming certification information where available; do not use faulty wine as a stand-in for natural wine.',relatedLessons:['terroir','organic','natural','petnat','flaws','skin-aging','sparkling']},
{id:'tasting-7',number:7,title:'Same wine, a different bite.',axis:'technique',wines:['Dry high-acid white','Off-dry Riesling','Light, gently tannic red'],concept:'Explore how salt, acidity, richness, and chilli change perception.',prompts:['Try a sip before and after a small bite; describe what seems different.','Ask whether a guest wants refreshment, a textural match, or a touch of sweetness.'],preparation:'Choose two or three styles. A guide can offer suitable salty, acidic, rich, and mildly spicy bites; check participant dietary needs and do not require any particular food.',relatedLessons:['acid-salt','richness','spice','seafood','preferences','acidity','riesling']},
{id:'tasting-8',number:8,title:'Two glasses and a good question.',axis:'grape',wines:['Fresh, dry white','Rounder white with known oak/texture choices','Lighter red','Fuller red with known tannin level'],concept:'Practice translating a guest’s words into a choice from the actual list.',prompts:['Role-play one of your recently completed guest conversations before choosing a glass.','Offer two options, confirm budget, and explain one useful difference without judging a preference.'],preparation:'Use two to four current restaurant wines and real menu prices. Have the guide alternate guest and server roles; there is no single correct bottle.',relatedLessons:['preferences','floor-chardonnay','floor-sauvignon','floor-oysters','floor-caymus','floor-mixed','flaws']},
];
